[package]
name = "sccache"
version = "0.2.1-pre"
authors = ["Ted Mielczarek <ted@mielczarek.org>", "Alex Crichton <alex@alexcrichton.com>"]
license = "Apache-2.0"
description = "Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."
repository = "https://github.com/mozilla/sccache/"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
keywords = ["ccache"]

[badges]
travis-ci = { repository = "mozilla/sccache" }
appveyor = { repository = "mozilla/sccache" }

[package.metadata.release]
sign-commit = true

[dependencies]
app_dirs = "1.1.1"
base64 = "0.5.2"
bincode = "0.8"
byteorder = "1.0"
chrono = { version = "0.3", optional = true }
clap = "2.23.0"
env_logger = "0.4"
error-chain = { version = "0.10", default-features = false }
fern = "0.3.5"
filetime = "0.1"
futures = "0.1.11"
futures-cpupool = "0.1"
hyper = { version = "0.11", optional = true }
hyper-tls = { version = "0.1", optional = true }
jsonwebtoken = { version = "2.0", optional = true }
libc = "0.2.10"
local-encoding = "0.2.0"
log = "0.3.6"
lru-disk-cache = { path = "lru-disk-cache", version = "0.1.0" }
native-tls = "0.1"
number_prefix = "0.2.5"
openssl = { version = "0.9", optional = true }
redis = { version = "0.8.0", optional = true }
regex = "0.2"
retry = "0.4.0"
ring = "0.9.0"
rust-crypto = { version = "0.2.36", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempdir = "0.3.4"
tempfile = "2.1.5"
time = "0.1.35"
tokio-core = "0.1.6"
tokio-io = "0.1"
tokio-process = "0.1"
tokio-proto = "0.1"
tokio-serde-bincode = "0.1"
tokio-service = "0.1"
tokio-tls = "0.1"
uuid = { version = "0.5", features = ["v4"] }
url = { version = "1.0", optional = true }
which = "1.0"
zip = { version = "0.2", default-features = false }

[dev-dependencies]
gcc = "0.3"
itertools = "0.6"

[target.'cfg(unix)'.dependencies]
daemonize = "0.2.3"
tokio-uds = "0.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2"
mio-named-pipes = "0.1"

[features]
default = ["s3"]
all = ["redis", "s3"]
s3 = ["chrono", "hyper", "hyper-tls", "rust-crypto", "simple-s3"]
simple-s3 = []
gcs = ["chrono", "hyper", "hyper-tls", "jsonwebtoken", "openssl", "url"]
# Enable features that require unstable features of Nightly Rust.
unstable = []

[profile.release]
debug = true

[workspace]
